version: '3'
services:
  web:
    build: .
    privileged: true
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./server:/neohub/server
    environment:
      - MONGO_HOST=db
  db:
    image: andresvidal/rpi3-mongodb3:latest
    restart: unless-stopped
    command: mongod
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - /data/db:/data/db
      - /data/configdb:/data/configdb